### ISSUE TITLE
Ghosting of animated text

### ISSUE THREAD

**Issue by dabell-cc** [vizzuhq/codeviz#16] opened 2023-02-24 22:21 UTC
Bars and text (especially) leaves persistent ghosting after animations, like the canvas is not cleared.
This persists and gets worse with further use. See axes text in this image:

![image](https://user-images.githubusercontent.com/8835326/221302431-64a9de55-9f2d-4058-ae2e-fbefe8ccf808.png)

Environment:
VSCode 1.75.2 Windows10
![image](https://user-images.githubusercontent.com/8835326/221302579-23e285d0-63a2-4de7-97ac-386f27499f4f.png)

**Comment by simzer** [comment] 2023-02-28 15:54
Hi, 
We couldn't reproduce this problem so far. 
Could you please check if you can see any related log in 'Developer Tools [Ctrl-Shift-I]'?
Also, could you attach the content of the related folder from the /.VSCodeCounter folder (if it is not sensitive data, it contains the list of files in the workspace and their stats)?
Also could you check if it works with other workspaces?
Thanks!

**Comment by schaumb** [comment] 2023-07-03 13:50
Closing due to insufficient data.

**Closed as completed by schaumb** 2023-07-03 13:50 UTC
